/************ Add: Sequences ***************/

/* Autogenerated Sequences */

CREATE SEQUENCE "layouts_Id_seq" INCREMENT BY 1;
COMMENT ON SEQUENCE "layouts_Id_seq" IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE "user_options_Id_seq" INCREMENT BY 1;
COMMENT ON SEQUENCE "user_options_Id_seq" IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE "user_pages_Id_seq" INCREMENT BY 1;
COMMENT ON SEQUENCE "user_pages_Id_seq" IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE "user_widget_Id_seq" INCREMENT BY 1;
COMMENT ON SEQUENCE "user_widget_Id_seq" IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE "users_Id_seq" INCREMENT BY 1;
COMMENT ON SEQUENCE "users_Id_seq" IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE "widgets_Id_seq" INCREMENT BY 1;
COMMENT ON SEQUENCE "widgets_Id_seq" IS 'DbWrench Autogenerated Sequence.';




/************ Update: Tables ***************/

/******************** Add Table: "layouts" ************************/

/* Build Table Structure */
CREATE TABLE "layouts"
(
	"Id" INTEGER DEFAULT nextval('"schemaA"."layouts_Id_seq"'::regclass) NOT NULL,
	name VARCHAR(255) NOT NULL,
	layout TEXT NOT NULL
);

/* Add Primary Key */
ALTER TABLE "layouts" ADD CONSTRAINT pklayouts
	PRIMARY KEY ("Id");


/******************** Add Table: "user_options" ************************/

/* Build Table Structure */
CREATE TABLE "user_options"
(
	"Id" INTEGER DEFAULT nextval('"schemaA"."user_options_Id_seq"'::regclass) NOT NULL,
	users_id INTEGER NOT NULL,
	background_color VARCHAR(255) NOT NULL,
	base_color VARCHAR(255) NOT NULL,
	secondary_color VARCHAR(255) NOT NULL,
	font_family VARCHAR(255) NOT NULL,
	layout_id INTEGER NOT NULL
);

/* Add Primary Key */
ALTER TABLE "user_options" ADD CONSTRAINT pkuser_options
	PRIMARY KEY ("Id");


/******************** Add Table: "user_pages" ************************/

/* Build Table Structure */
CREATE TABLE "user_pages"
(
	"Id" INTEGER DEFAULT nextval('"schemaA"."user_pages_Id_seq"'::regclass) NOT NULL,
	users_id INTEGER NOT NULL,
	content TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL
);

/* Add Primary Key */
ALTER TABLE "user_pages" ADD CONSTRAINT pkuser_pages
	PRIMARY KEY ("Id");


/******************** Add Table: "user_widget" ************************/

/* Build Table Structure */
CREATE TABLE "user_widget"
(
	"Id" INTEGER DEFAULT nextval('"schemaA"."user_widget_Id_seq"'::regclass) NOT NULL,
	users_id INTEGER NOT NULL,
	widgets_id INTEGER NOT NULL,
	position INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL
);

/* Add Primary Key */
ALTER TABLE "user_widget" ADD CONSTRAINT pkuser_widget
	PRIMARY KEY ("Id");


/******************** Add Table: "users" ************************/

/* Build Table Structure */
CREATE TABLE "users"
(
	"Id" INTEGER DEFAULT nextval('"schemaA"."users_Id_seq"'::regclass) NOT NULL,
	"usersName" VARCHAR(50) NOT NULL,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	token VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL
);

/* Add Primary Key */
ALTER TABLE "users" ADD CONSTRAINT pkusers
	PRIMARY KEY ("Id");


/******************** Add Table: "widgets" ************************/

/* Build Table Structure */
CREATE TABLE "widgets"
(
	"Id" INTEGER DEFAULT nextval('"schemaA"."widgets_Id_seq"'::regclass) NOT NULL,
	name VARCHAR(255) NOT NULL,
	folder_name VARCHAR(255) NOT NULL
);

/* Add Primary Key */
ALTER TABLE "widgets" ADD CONSTRAINT pkwidgets
	PRIMARY KEY ("Id");





/************ Add Foreign Keys ***************/

/* Add Foreign Key: fk_user_options_layouts */
ALTER TABLE "user_options" ADD CONSTRAINT fk_user_options_layouts
	FOREIGN KEY (layout_id) REFERENCES "layouts" ("Id")
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_user_options_users */
ALTER TABLE "user_options" ADD CONSTRAINT fk_user_options_users
	FOREIGN KEY (users_id) REFERENCES "users" ("Id")
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_user_pages_users */
ALTER TABLE "user_widget" ADD CONSTRAINT fk_user_pages_users
	FOREIGN KEY (users_id) REFERENCES "users" ("Id")
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_user_pages_widgets */
ALTER TABLE "user_widget" ADD CONSTRAINT fk_user_pages_widgets
	FOREIGN KEY (widgets_id) REFERENCES "widgets" ("Id")
	ON UPDATE NO ACTION ON DELETE NO ACTION;