
CREATE TABLE `layouts` (`id` INT(1) AUTO_INCREMENT NOT NULL, `name` VARCHAR(255) NOT NULL, `layout` TEXT NOT NULL, PRIMARY KEY(id));

CREATE TABLE `user_options` (`id` INT(1) AUTO_INCREMENT NOT NULL, `user_id` INT(1) NOT NULL, `background_color` VARCHAR(255) NOT NULL, base_color VARCHAR(255) NOT NULL, secondary_color VARCHAR(255) NOT NULL, font_family VARCHAR(255) NOT NULL, layout_id INTEGER NOT NULL, PRIMARY KEY(`id`));

CREATE TABLE `user_pages` (`id` INT(1) AUTO_INCREMENT NOT NULL, user_id INT(1) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(`id`));

CREATE TABLE `user_widget` (`id` INT(1) AUTO_INCREMENT NOT NULL, user_id INT(1) NOT NULL, widget_id INT(1) NOT NULL, position INT(1) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(`id`));

CREATE TABLE `users` (`id` INT(1) AUTO_INCREMENT NOT NULL, `username` VARCHAR(255) NOT NULL, `password` VARCHAR(255) NOT NULL, `email` VARCHAR(255) NOT NULL, `token` VARCHAR(255) NOT NULL, `moderator` ENUM('0', '1') NOT NULL DEFAULT '0', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (`id`));

CREATE TABLE `widgets` (`id` INT(1) AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, directory VARCHAR(255) NOT NULL, disabled ENUM('0', '1') NOT NULL DEFAULT '1', PRIMARY KEY(`id`));

ALTER TABLE `user_options` ADD CONSTRAINT fk_user_options_layouts FOREIGN KEY(layout_id) REFERENCES layouts (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `user_options` ADD CONSTRAINT fk_user_options_users FOREIGN KEY (user_id) REFERENCES users (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `user_widget` ADD CONSTRAINT fk_user_pages_users FOREIGN KEY (user_id) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `user_widget` ADD CONSTRAINT fk_user_pages_widgets FOREIGN KEY (`widget_id`) REFERENCES `widgets` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;

